// ─── /api/canvas/itinerary ──────────────────────────────────────────────────
// Day-by-day "things to do" for a leg, generated by Gemini 2.5 Pro with
// Google Search grounding and enriched with Google Places (photos, ratings,
// lat/lon, hours). Used by the leg's ItineraryPanel.
//
// GET ?city=Paris&days=4&interests=food,art   → DestinationItinerary | 503
//
// The endpoint is GET so Railway's CDN can cache it (24h s-maxage). The
// helper itself also caches in-process for 24h so a page refresh on the
// same leg is free.

import { NextRequest, NextResponse } from 'next/server';
import { fetchItinerary } from '@/lib/canvas/itinerary';
import { getClientIp, rateLimit } from '@/lib/rate-limit';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const CACHE_HEADERS = {
  'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=86400',
};

export async function GET(req: NextRequest) {
  const ip = getClientIp(req);
  if (!rateLimit(`ip:canvas-itinerary:${ip}`, 10, 60_000)) {
    return NextResponse.json(
      { error: 'Too many itinerary requests. Please wait a moment and try again.' },
      { status: 429, headers: { 'Retry-After': '60' } },
    );
  }

  const city = (req.nextUrl.searchParams.get('city') ?? '').trim();
  if (!city || city.length < 2 || city.length > 100) {
    return NextResponse.json({ error: 'Missing or invalid city' }, { status: 400 });
  }

  const daysRaw = parseInt(req.nextUrl.searchParams.get('days') ?? '3', 10);
  const days    = Number.isFinite(daysRaw) ? Math.max(1, Math.min(7, daysRaw)) : 3;

  const interestsParam = (req.nextUrl.searchParams.get('interests') ?? '').trim();
  const interests = interestsParam
    ? interestsParam.split(',').map(s => s.trim()).filter(Boolean).slice(0, 6)
    : [];

  const itinerary = await fetchItinerary(city, days, interests);
  if (!itinerary) {
    return NextResponse.json(
      { error: 'Could not generate itinerary for this destination.' },
      { status: 502 },
    );
  }

  return NextResponse.json(itinerary, { headers: CACHE_HEADERS });
}
